ci: validate branch name in preview release workflow

diff --git a/.github/workflows/preview-release-on-comment.yml b/.github/workflows/preview-release-on-comment.yml
--- a/.github/workflows/preview-release-on-comment.yml
+++ b/.github/workflows/preview-release-on-comment.yml
@@ -30,6 +30,14 @@ jobs:
         uses: xt0rted/pull-request-comment-branch@v1
         id: comment-branch
 
+      - name: Validate branch name
+        run: |
+          BRANCH_NAME=${{ steps.comment-branch.outputs.head_ref }}
+          if [[ ! "$BRANCH_NAME" =~ ^preview/[a-zA-Z0-9_-]+$ ]]; then
+            echo "Invalid branch name. Exiting workflow."
+            exit 1
+          fi
+
       - name: Ensure branch name matches 'preview/**'
         run: |
           BRANCH_NAME=${{ steps.comment-branch.outputs.head_ref }}
